collections:
  - name: "blog"
    label: "Άρθρα"
    folder: "blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Τίτλος", name: "title", widget: "string" }
      - { label: "Ημερομηνία", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["blog"] }
      - { label: "Layout", name: "layout", widget: "hidden", default: "post.njk" }
      - { label: "Περιεχόμενο", name: "body", widget: "markdown" }
