backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Άρθρα"
    folder: "blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Τίτλος", name: "title", widget: "string" }
      - { label: "Ημερομηνία", name: "date", widget: "datetime" }
      - { label: "Εικόνα", name: "thumbnail", widget: "image" }
      - { label: "Περιεχόμενο", name: "body", widget: "markdown" }
